# Generated by Django 4.2.16 on 2024-12-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='custom_user_table',
        ),
    ]
