# Generated by Django 4.2.16 on 2024-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user reg', 'verbose_name_plural': 'my users'},
        ),
    ]
